apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cozystack-scheduler
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/status
      - pods/binding
      - nodes
      - namespaces
      - persistentvolumes
      - persistentvolumeclaims
      - services
      - replicationcontrollers
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - pods/binding
    verbs: ["create"]
  - apiGroups: [""]
    resources:
      - pods/status
    verbs: ["patch", "update"]
  - apiGroups: [""]
    resources:
      - events
      - endpoints
    verbs: ["create", "patch", "update"]
  - apiGroups: ["apps"]
    resources:
      - replicasets
      - statefulsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources:
      - csinodes
      - csidrivers
      - storageclasses
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups: ["cozystack.io"]
    resources:
      - schedulingclasses
    verbs: ["get", "list", "watch"]
